version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-achat
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: achatdb
      MYSQL_USER: achatuser
      MYSQL_PASSWORD: achatpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  achat:
    image: alaabenjaber/achat:1.0.0
    container_name: achat-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/achatdb
      SPRING_DATASOURCE_USERNAME: achatuser
      SPRING_DATASOURCE_PASSWORD: achatpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8089:8089"

volumes:
  db_data:
